#!/usr/bin/env bash

# Sets
set shell sh
set shellopts "-eu"
set ifs "\n"
set scrolloff 10
set cursorpreviewfmt "\033[7;2m"
set previewer "~/.config/lf/previewer"
set icons
set hidden
set period 1
set ignorecase
set statfmt "\033[7;36m %M \033[0m| \033[36m%p\033[0m| %c| %u| %g| %S| %t| -> %l"
set dupfilefmt "%b-%n%e"
set promptfmt ""
set mouse true

# Commands
cmd on-redraw &{{
  if [ $lf_width -le 40 ]; then
    lf -remote "send $id set preview false"
    lf -remote "send $id set ratios 1"
  elif [ $lf_width -le 80 ]; then
    lf -remote "send $id set ratios 1:1"
    lf -remote "send $id set preview true"
  elif [ $lf_width -le 160 ]; then
    lf -remote "send $id set ratios 1:1:2"
    lf -remote "send $id set preview true"
  else
    lf -remote "send $id set ratios 1:1:2:4"
    lf -remote "send $id set preview true"
  fi
  lf -remote "send $id :on-cd"
}}

cmd on-cd &{{
  bright="\033[1m"
  blue="$(tput setaf 4)"
  reset="\033[0m"
  if [ $lf_width -le 40 ]; then
    lf -remote "send $id set promptfmt \"$bright$blue$(basename $PWD)$reset\""
  else
    lf -remote "send $id set promptfmt \"\033[32;1m%u@%h\033[0m:\033[34;1m%d\033[0m\033[1m%f\033[0m\""
  fi
}}

cmd on-load &{{
  sleep 0.1
  lf -remote "send $id :on-redraw"
  lf -remote "send $id :on-cd"
}}

# cmd drag-to %{{

# }}

cmd drag-from %{{
  dragon-drop -x -a $fx
}}

cmd paste-img &{{
  name="pasted-image"
  new_name="$name"
  i=0
  while [ -f "$new_name.png" ]; do
    i=$((i+1))
    new_name="$name-$i"
  done
  name="$new_name.png"

  if [ "$XDG_SESSION_TYPE" == "wayland" ]; then
    [ -z "$(wl-paste --list-types | grep png 2>/dev/null)" ] && notify-send "Clipboard selection not an image" && exit 0
    wl-paste -t image/png > "$name"
  else
    [ -z "$(xclip -selection clipboard -o -t TARGETS | grep png 2>/dev/null)" ] && notify-send "Clipboard selection not an image" && exit 0
    xclip -selection clipboard -t image/png -o > "$name"
  fi
}}

cmd term &{{
  $HOME/.dotfiles/.scripts/swallow.sh $TERMINAL -e --cwd "$PWD"
}}

cmd open &{{
  case $(file --mime-type -Lb "$f") in
    text/* | */json | */javascript)
      case $f in
        *.RPP | *.rpp | *.RPP-bak | *.rpp-bak | *.kdenlive) $HOME/.dotfiles/.scripts/swallow.sh xdg-open "$f" ;;
        *) $HOME/.dotfiles/.scripts/lf-helix.sh "$f" ;;
      esac
      ;;
    *)
      case $f in
        *.nelua | *.env | *.tsx | *.ts)
          $HOME/.dotfiles/.scripts/lf-helix.sh "$f"
          ;;
        *)
          $HOME/.dotfiles/.scripts/swallow.sh xdg-open "$f"
          ;;
      esac
      ;;
  esac
}}

cmd open-with &{{
  $HOME/.dotfiles/.scripts/swallow.sh eval "$@ $f"
}}

# extract the current file with the right command
# (xkcd link: https://xkcd.com/1168/)
cmd extract %{{
  set -f
  name="$f-extracted"
  mkdir "$name"
  cd $name
  case $f in
    *.tar.bz|*.tar.bz2|*.tbz|*.tbz2) tar xjvf $f;;
    *.tar.gz|*.tgz) tar xzvf $f;;
    *.tar.xz|*.txz) tar xJvf $f;;
    *.zip) unzip $f;;
    *.rar) unrar x $f;;
    *.7z) 7z x $f;;
  esac
}}

# compress current file or selected files with tar and gunzip
cmd tar %{{
  set -f
  mkdir $1
  cp -r $fx $1
  tar czf $1.tar.gz $1
  rm -rf $1
}}

# compress current file or selected files with zip
cmd zip %{{
  set -f
  mkdir $1
  cp -r $fx $1
  zip -r $1.zip $1
  rm -rf $1
}}

# compress current file or selected files with 7z
cmd 7z %{{
  set -f
  mkdir $1
  cp -r $fx $1
  7z a $1.7z $1
  rm -rf $1
}}

cmd delete %{{
  IFS=";" read -r -a files <<< "$(echo "$fx" | tr "\n" ";")"
  len=${#files[@]}

  result=$( [ "$len" -gt 1 ] && echo "files" || echo "file" )

  question="Trash ${len} ${result}?"

  for file in "${files[@]}"; do
    question="$question\n  $(basename "$file")"
  done

  yes="Yes"
  no="No"
  options="$yes\n$no"

  chosen="$(echo -e "$options" | rofi -theme-str 'inputbar {children: [prompt];}' -i -show -p "$(echo -e "$question")" -dmenu -selected-row 0)"
  case $chosen in
    $yes)
      echo "Deleting..."
      for file in "${files[@]}"; do
        trash-put "$(basename "$file")"
      done
      ;;
  esac
}}

cmd trash-empty %{{
  question="Are you sure you want to empty your trash directory:"
  yes="Yes"
  no="No"
  options="$yes\n$no"

  chosen="$(echo -e "$options" | rofi -theme-str 'entry { enabled: false;}' -i -show -p "$question" -dmenu -selected-row 0)"
  case "$chosen" in
    "$yes")
      echo "Emptying trash directory..."
      trash-empty
      echo "Trash directory emptied"
      ;;
  esac
}}

cmd rename-in-editor ${{
  set shellopts '-eu'
  set ifs "\n"

	index=$(mktemp /tmp/lf-rename-in-editor-index.XXXXXXXXXX)
	[ -n "${fs}" ] && echo "$fs" > $index || echo "$f" > $index

	index_edit=$(mktemp /tmp/lf-rename-in-editor.XXXXXXXXXX)
	cat $index > $index_edit
	$EDITOR $index_edit
	if [ $(cat $index | wc -l) -eq $(cat $index_edit | wc -l) ]; then
		max=$(($(cat $index | wc -l)+1))
		counter=1
		while [ $counter -le $max ]; do
			a="$(cat $index | sed "${counter}q;d")"
			b="$(cat $index_edit | sed "${counter}q;d")"
			counter=$(($counter+1))

			[ "$a" = "$b" ] && continue
			[ -e "$b" ] && echo "File exists: $b" && continue
			mv "$a" "$b"
		done
	else
		notify-send "lf-rename-in-editor" "ERROR: More lines than selected files"
	fi
	rm $index $index_edit
}}

cmd create %{{
  for name in "$@"; do
    if [[ "$name" == */ ]]; then
      mkdir -p "$name"
    else
      DIR_PATH=$(dirname "$name")
      mkdir -p "$DIR_PATH"
      touch "$name"
    fi
  done
}}

cmd chmod %{{
  if [ -z "${1+x}" ] || [ "$1" == "" ]; then
    echo "No params set" >&2
    exit 1
  fi

  IFS=";" read -r -a files <<< "$(echo "$fx" | tr "\n" ";")"
  for file in "${files[@]}"; do
    chmod $1 "$file"
  done
  lf -remote "send $id reload"
}}

cmd copy-absolute-path &{{
  IFS=";" read -r -a files <<< "$(echo "$fx" | tr "\n" ";")"
  for file in "${files[@]}"; do
    $HOME/.scripts/clip.sh add "$file"
  done
  notify-send "File paths added to clipboard"
}}

cmd copy-name-w-ext &{{
  IFS=";" read -r -a files <<< "$(echo "$fx" | tr "\n" ";")"
  for file in "${files[@]}"; do
    $HOME/.scripts/clip.sh add $(basename "$file")
  done
  notify-send "File names added to clipboard"
}}

cmd copy-name-wo-ext &{{
  IFS=";" read -r -a files <<< "$(echo "$fx" | tr "\n" ";")"
  for file in "${files[@]}"; do
    $HOME/.scripts/clip.sh add "$(basename "$file" | sed "s/\.[^.]*$//")"
  done
  notify-send "File names added to clipboard"
}}

cmd copy-parent-dir-path &{{
  IFS=";" read -r -a files <<< "$(echo "$fx" | tr "\n" ";")"
  for file in "${files[@]}"; do
    $HOME/.scripts/clip.sh add $(dirname "$file")
  done
  notify-send "Parent directory paths added to clipboard"
}}

cmd copy-image &{{
  set +e # So i can actually check if it's an image and pass a notfication
  IFS=";" read -r -a files <<< "$(echo "$fx" | tr "\n" ";")"
  for file in "${files[@]}"; do
    is_img=$(file -Lb --mime-type -- "$file" | grep "image/" 2>/dev/null)
    if [ -z "$is_img" ]; then
      notify-send "'$file' is not an image"
      exit 1
    fi
    if [ "$XDG_SESSION_TYPE" == "wayland" ]; then
      wl-copy -t image/png < "$file"
    else
      xclip -selection clipboard -target image/png -i "$file"
    fi
    $HOME/.scripts/clip.sh recopy
  done
}}

cmd check-storage %{{
  df -h --output=size,used,avail,pcent | awk 'NR==2 {printf "Total Size: %s, Used: %s, Available: %s, Percent: %s\n", $1, $2, $3, $4}'
}}

cmd full-clear &{{
  lf -remote "send $id clear"
  lf -remote "send $id unselect"
  lf -remote "send $id visual-discard"
}}

# Bindings

# Unbinds
map c
map d
map V
map p
map G
map i
map ";"

map <m-2> open
map <m-3> push :open-with<space>

# Sort
map sa :{{ set sortby atime; set info atime; set reverse!; }}
map sb :{{ set sortby btime; set info btime; set reverse!; }}
map sc :{{ set sortby ctime; set info ctime; set reverse!; }}
map se :{{ set sortby ext; set info; set reverse!; }}
map sn :{{ set sortby natural; set info; set reverse!; }}
map ss :{{ set sortby size; set info size; set reverse!; }}
map st :{{ set sortby time; set info time; set reverse!; }}

map <c-t> :term

map ge bottom

map <c-q> quit

nmap v visual
vmap v visual-accept

map <esc> full-clear
map "." set hidden!

map a push :create<space>

map D :drag-from; full-clear
map P paste-img

map d delete
map <delete> delete
map u ${{
  echo
  trash-restore
  clear
}}
map p :paste; full-clear
map x cut
map y copy

map R rename-in-editor

map e open
map o open
map <enter> open
map O push :open-with<space>

map <c-r> %{{
  lf -remote "send $id reload"
  lf -remote "send $id redraw"
  lf -remote "send $id source '~/.config/lf/lfrc'"
  sleep 0.2
  echo "Config Reloaded"
}}

map ca copy-absolute-path
map cn copy-name-w-ext
map ce copy-name-wo-ext
map cp copy-parent-dir-path
map ci copy-image

map cs check-storage

# show the result of execution of previous commands
map ` !true

# Movement
map gd cd ~/Documents
map gw cd ~/Downloads
map gp cd ~/Pictures
map gs cd ~/Pictures/screenshots
map ga cd ~/Games
map gv cd ~/Videos
map gm cd ~/Music
map grr cd ~/Documents/REAPER\ Media
map grs cd ~/Documents/REAPER\ Media/Songs
map grb cd ~/Documents/REAPER\ Media/Beats
map gco cd ~/.config
map gcp cd ~/Documents/code-projects
map gce cd ~/Documents/code-projects/external-work
map gcn cd ~/Documents/code-projects/languages/nelua
map gcl cd ~/Documents/code-projects/languages/lua
map gcs cd ~/.scripts
map gcd cd ~/.dotfiles
map gt cd ~/.local/share/Trash/files
