#!/usr/bin/env bash

set -C -f -e -x

image() {
  chafa -f sixel -s "$2x$3" --animate off --polite on -t 1 --bg black "$1"
}

resize_dimensions() {
  ORIGINAL_WIDTH=$1
  ORIGINAL_HEIGHT=$2

  # Calculate new dimensions while maintaining the aspect ratio
  ASPECT_RATIO=$(bc -l <<< "$ORIGINAL_WIDTH / $ORIGINAL_HEIGHT")

  if (( $(echo "$ASPECT_RATIO < 1.77" | bc -l) )); then
      MAX_WIDTH=144
      MAX_HEIGHT=81
  else
      MAX_WIDTH=80
      MAX_HEIGHT=40
  fi

  if (( ORIGINAL_WIDTH > ORIGINAL_HEIGHT )); then
    # Landscape
    NEW_WIDTH=$MAX_WIDTH
    NEW_HEIGHT=$(bc -l <<< "$NEW_WIDTH / $ASPECT_RATIO")
  else
    # Portrait or square
    NEW_HEIGHT=$MAX_HEIGHT
    NEW_WIDTH=$(bc -l <<< "$NEW_HEIGHT * $ASPECT_RATIO")
  fi

  # Ensure new dimensions are integers
  NEW_WIDTH=${NEW_WIDTH%.*}
  NEW_HEIGHT=${NEW_HEIGHT%.*}

  echo "$NEW_WIDTH $NEW_HEIGHT"
}


CACHE_ROOT="/tmp/lf"

if [ ! -d "$CACHE_ROOT" ]; then
  mkdir "$CACHE_ROOT"
fi

case "$(file -Lb --mime-type -- "$1")" in
  image/*)
    image "$1" "$2" "$3"
    ;;
  text/*|*/json|*/javascript)
    bat -p --theme=ansi --terminal-width "$(($4-2))" -f "$1"
    ;;
  video/*)
    cache_stat=$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | cut -d' ' -f1)
    CACHE="${CACHE_ROOT}/thumb.$cache_stat"
    CACHE="$CACHE.png"
    if [ ! -f "$CACHE" ]; then
      ffmpegthumbnailer -i "$1" -o "$CACHE" -s 0
      cached_stat=$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$cache_stat")" | sha256sum | cut -d' ' -f1)
      if [ $cached_stat != $cache_stat ]; then
        ffmpegthumbnailer -i "$1" -o "$CACHE" -s 0
      fi
    fi
    read width height <<< "$(file "$CACHE" | grep -Po "\d+ x \d+" | sed 's/ x / /')"
    image "$CACHE" $(resize_dimensions $width $height)
    ;;
  */pdf)
    cache_stat=$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | cut -d' ' -f1)
    CACHE="${CACHE_ROOT}/thumb.$cache_stat"
    CACHE="$CACHE.jpg"
    if [ ! -f "$CACHE" ]; then
      magick "${1}[0]" "$CACHE"
    else
      cached_stat=$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$cache_stat")" | sha256sum | cut -d' ' -f1)
      if [ $cached_stat != $cache_stat ]; then
        magick "${1}[0]" "$CACHE"
      fi
    fi
    image "$CACHE" "40" "60"
    ;;
  *)
    case "$1" in
      *.tgz|*.tar.gz) tar tzf "$1";;
      *.tar.bz2|*.tbz2) tar tjf "$1";;
      *.tar.txz|*.txz) xz --list "$1";;
      *.tar) tar tf "$1";;
      *.zip|*.jar|*.war|*.ear|*.oxt) unzip -l "$1";;
      *.rar) unrar l "$1";;
      *.7z) 7z l "$1";;
      *)
        echo -e "----- FILE INFO -----\n"
        stat "$1"
    esac
    ;;
esac
