#!/bin/sh

set -C -f -e

image() {
  chafa -f sixel -s "$2x$3" --animate off --polite on -t 1 --bg black "$1"
}

CACHE_ROOT=${XDG_CACHE_HOME:-$HOME/.cache}/lf

if [ ! -d "$CACHE_ROOT" ]; then
  mkdir "$CACHE_ROOT"
fi

case "$(file -Lb --mime-type -- "$1")" in
  image/*)
    image "$1" "$2" "$3"
    ;;
  text/*|*json)
    bat -p --theme=ansi --terminal-width "$(($4-2))" -f "$1"
    ;;
  */pdf)
    CACHE="${CACHE_ROOT}/thumb.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | cut -d' ' -f1)"
    CACHE="$CACHE.jpg"
    if [ ! -f "$CACHE" ] || [ "$1" -nt "$CACHE" ]; then
      pdftoppm -jpeg -f 1 -singlefile "$1" "$CACHE"
    fi
    image "$CACHE" "40" "60"
    ;;
  *)
    echo -e "----- FILE INFO -----\n"
    stat "$1"
    ;;
esac
