#!/bin/sh

set -C -f -e -x

image() {
  chafa -f sixel -s "$2x$3" --animate off --polite on -t 1 --bg black "$1"
}

CACHE_ROOT=${XDG_CACHE_HOME:-$HOME/.cache}/lf

if [ ! -d "$CACHE_ROOT" ]; then
  mkdir "$CACHE_ROOT"
fi

case "$(file -Lb --mime-type -- "$1")" in
  image/*)
    image "$1" "$2" "$3"
    ;;
  text/*|*json)
    bat -p --theme=ansi --terminal-width "$(($4-2))" -f "$1"
    ;;
  video/*)
    cache_stat=$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | cut -d' ' -f1)
    CACHE="${CACHE_ROOT}/thumb.$cache_stat"
    CACHE="$CACHE.jpg"
    if [ ! -f "$CACHE" ]; then
      ffmpegthumbnailer -i "$1" -o "$CACHE" -s 0
      cached_stat=$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$cache_stat")" | sha256sum | cut -d' ' -f1)
      if [ $cached_stat != $cache_stat ]; then
        ffmpegthumbnailer -i "$1" -o "$CACHE" -s 0
      fi
    fi
    image "$CACHE" "80" "45"
    ;;
  */pdf)
    cache_stat=$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | cut -d' ' -f1)
    CACHE="${CACHE_ROOT}/thumb.$cache_stat"
    CACHE="$CACHE.jpg"
    if [ ! -f "$CACHE" ]; then
      magick "${1}[0]" "$CACHE"
    else
      cached_stat=$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$cache_stat")" | sha256sum | cut -d' ' -f1)
      if [ $cached_stat != $cache_stat ]; then
        magick "${1}[0]" "$CACHE"
      fi
    fi
    image "$CACHE" "40" "60"
    ;;
  *)
    case "$1" in
      *.tgz|*.tar.gz) tar tzf "$1";;
      *.tar.bz2|*.tbz2) tar tjf "$1";;
      *.tar.txz|*.txz) xz --list "$1";;
      *.tar) tar tf "$1";;
      *.zip|*.jar|*.war|*.ear|*.oxt) unzip -l "$1";;
      *.rar) unrar l "$1";;
      *.7z) 7z l "$1";;
      *)
        echo -e "----- FILE INFO -----\n"
        stat "$1"
    esac
    ;;
esac
