#### Aliases ####
alias global bc delete-buffer
alias global bc! delete-buffer!

#### Keybindings ####
map global normal <a-1> ':buffer-previous<ret>'
map global normal <a-2> ':buffer-next<ret>'
map global normal <a-q> ':db<ret>'
map global normal <a-o> :edit-kakrc<ret>

map global normal <ret> <o>
map global normal <esc> ,hl  -docstring  'Clear Multi-cursor Selection'
map global normal <a-esc> <a-,>hl  -docstring  'Clear Multi-cursor Selection'

map global normal <c-a> ':inc-dec-modify-numbers + 1 <ret>'
map global normal <c-x> ':inc-dec-modify-numbers - 1 <ret>'
map global normal <c-n> ':edit -scratch<ret>'
map global normal <c-q> ':q<ret>'
map global normal <c-s> ':w<ret>'

map global normal <backspace> h<a-d>

map global normal F ':format<ret>'

define-command _clipboard-paste -hidden -params 1 %{
  eval %sh{
    content=$(
      ~/.scripts/clip.sh out                     \
      | sed 's/</#:____lt____:#/g'               \
      | sed 's/>/#:____gt____:#/g'               \
      | sed -E 's/#:____([a-z]{2})____:#/<\1>/g' \
      | sed 's/;/<semicolon>/g'                  \
      | sed 's/$/<ret>/g;'                       \
      | sed 's/ /<space>/g'                      \
      | sed 's/\t/<tab>/g'                       \
      | sed ':a;N;$!ba;s/\n//g'                  \
      | sed 's/<ret>$//'                         \
    )
    echo "exec $1${content}"
  }
}
define-command clipboard-paste-before %{
  _clipboard-paste "i"
}
define-command clipboard-paste-after %{
  _clipboard-paste "a"
}
define-command clipboard-paste-replace %{
  _clipboard-paste "di"
}
map global user <p> ':clipboard-paste-before<ret><esc>' -docstring 'Paste clipboard to buffer before cursor'
map global user <P> ':clipboard-paste-after<ret><esc>' -docstring 'Paste clipboard to buffer after cursor'
map global user <r> ':clipboard-paste-replace<ret><esc>' -docstring 'Replace buffer selection with clipboard'

map global user <B> ':pick-buffers<ret>' -docstring 'Pick buffer'
map global user <b> ':enter-user-mode buffers<ret>' -docstring 'Enter buffer mode'
map global user <c> ':comment-line<ret>' -docstring 'Toggle line comment'
map global user <C> ':comment-block<ret>' -docstring 'Toggle block comment'
map global user <y> ':nop %sh{~/.scripts/clip.sh add "$kak_selection"}<ret>' -docstring 'Copy selection to clipboard'
map global user <f> ':nop %sh{~/.scripts/kak-fzf.sh pick }<ret>' -docstring 'Open fuzzy file picker'
map global user <o> ':nop %sh{~/.scripts/kak-fzf.sh pick "$kak_buffile"}<ret>' -docstring "Open fuzzy file picker at current file's directory"
map global user </> ':nop %sh{~/.scripts/kak-fzf.sh global_search}<ret>' -docstring "Open global search text picker"

map global user w ":jumpJump<ret>"
map global user W ":jumpJump -extend<ret>"
map global user <a-w> ":jumpJump -add<ret>"

declare-user-mode run
map global normal <semicolon> ':enter-user-mode run<ret>'
map global run  t ':nop %sh{~/.scripts/kak-term.sh down 30}<ret>' -docstring 'Open Terminal Pane'
map global run  f ':nop %sh{~/.scripts/kak-term.sh left 20 lf "$kak_buffile"}<ret>' -docstring 'Open File manager pane'
map global run  l ':nop %sh{~/.scripts/kak-term.sh down 40 lazygit}<ret>' -docstring 'Open Lazygit pane'
map global run  r ':nop %sh{~/.scripts/kak-run.sh "$kak_buffile"}<ret>' -docstring 'Run current file interm'
map global run  c ':nop %sh{~/.scripts/kak-run.sh "$kak_buffile" true}<ret>' -docstring 'Run current file and pipe output to fzf picker'
map global run  s '| sort<ret>' -docstring 'Sort selection'

declare-user-mode match
declare-user-mode match-tag
map global normal m ':enter-user-mode match<ret>'
map global match m m -docstring 'Match next matching pair'
map global match i ':match-inside<ret>' -docstring 'Match inside object'
map global match a ':match-around<ret>' -docstring 'Match around object'
map global match n ':match-next<ret>' -docstring 'Match next object'
map global match p ':match-prev<ret>' -docstring 'Match previous object'
map global match s ':match-surround-add<ret>' -docstring 'Surround selection with character'
map global match d ':match-surround-delete<ret>' -docstring 'Delete selection''s surrounding character'
map global match r ':match-surround-replace<ret>' -docstring 'Replace selection''s surrounding character'

define-command -hidden select-prev-word-part %{
  exec <a-/>[A-Z][a-z]+|[A-Z]+|[a-z]+<ret>
}
define-command -hidden select-next-word-part %{
  exec /[A-Z][a-z]+|[A-Z]+|[a-z]+<ret>
}
define-command -hidden extend-prev-word-part %{
  exec <a-?>[A-Z][a-z]+|[A-Z]+|[a-z]+<ret>
}
define-command -hidden extend-next-word-part %{
  exec ?[A-Z][a-z]+|[A-Z]+|[a-z]+<ret>
}
map global normal <a-w> :select-next-word-part<ret>
map global normal <a-W> :extend-next-word-part<ret>
map global normal <a-b> :select-prev-word-part<ret>
map global normal <a-B> :extend-prev-word-part<ret>

#### hooks ####
hook global BufCreate .* %{
  expandtab
}

declare-option -docstring "name of the git branch holding the current buffer" \
  str git_branch

hook global WinCreate /.* %{
  hook window NormalIdle .* %{
    eval %sh{
      branch=$(cd "$(dirname "${kak_buffile}")" && git rev-parse --abbrev-ref HEAD 2>/dev/null)
      if [ -n "${branch}" ]; then
        printf 'set window git_branch " %%{%s}"' "${branch}"
      fi
    }
  }

  hook buffer NormalIdle .* %{
    try %{
      eval %sh{
        [ "$kak_modified" = true ] && echo "write"

        # modified=""
        # [ "$kak_modified" = true ] && modified="[+]"
        bufname=$(echo $kak_bufname | sed 's/[.\*+?[^$()|{}]/\\&/g; s/\//\\\//g;')
        buflist=$(echo $kak_buflist | sed 's/[.\*+?[^$()|{}]/\\&/g; s/\//\\\//g;')
        buffers=$(echo "$buflist" | sed "s/\\\\//g" | sed 's/ *\*debug\* *//' | sed "s/\($bufname\)/>\1/")
        printf 'set buffer buffers "%%{%s}"' "${buffers}"

      }
    }
  }
}

declare-option -docstring "Current mode" \
  str mode 'NORMAL'

hook global ModeChange .* %{
  eval %sh{
    new_mode=$(echo $kak_hook_param | cut -d ':' -f 3 | sed 's/.*/\U&/' 2>/dev/null)
    printf 'set window mode "%%{%s}"' "${new_mode}"
  }
}

declare-option -docstring "Curretly open buffers" \
    str buffers


set global modelinefmt '{cyan}%opt{git_branch}{default} | %opt{buffers} | %val{cursor_line}:%val{cursor_char_column} | %opt{mode} | %val{selection_count} | '

hook global InsertCompletionShow .* %{
  map window insert <tab>   '<c-n>'
  map window insert <s-tab> '<c-p>'
  # map window insert <esc>   '<c-o>'
}
hook global InsertCompletionHide .* %{
  unmap window insert <tab>   '<c-n>'
  unmap window insert <s-tab> '<c-p>'
  # unmap window insert <esc>   '<c-o>
}

hook global -once KakBegin .* %{
  eval %sh{kak-lsp}
}

hook global WinCreate /.* %{
  lsp-enable-window
  hook global -once -always WinClose .* %{
    lsp-disable-window
  }
  set-option global modelinefmt "%opt{lsp_modeline} %opt{modelinefmt}"
}

map global user l ':enter-user-mode lsp<ret>' -docstring 'LSP mode'

map global goto d <esc>:lsp-definition<ret> -docstring 'LSP definition'
map global goto r <esc>:lsp-references<ret> -docstring 'LSP references'
map global goto y <esc>:lsp-type-definition<ret> -docstring 'LSP type definition'

map global insert <tab> '<a-;>:try lsp-snippets-select-next-placeholders catch %{ execute-keys -with-hooks <lt>tab> }<ret>' -docstring 'Select next snippet placeholder'

map global object a '<a-semicolon>lsp-object<ret>' -docstring 'LSP any symbol'
map global object <a-a> '<a-semicolon>lsp-object<ret>' -docstring 'LSP any symbol'
map global object f '<a-semicolon>lsp-object Function Method<ret>' -docstring 'LSP function or method'
map global object t '<a-semicolon>lsp-object Class Interface Module Namespace Struct<ret>' -docstring 'LSP class or module'
map global object d '<a-semicolon>lsp-diagnostic-object error warning<ret>' -docstring 'LSP errors and warnings'
map global object D '<a-semicolon>lsp-diagnostic-object error<ret>' -docstring 'LSP errors'

hook global BufWritePost /.* %{
  try %{ exec -draft "%%s\h+$<ret>d" } # Trim trailing new lines
  try %{ exec -draft "%%s\t<ret>i<space><space><esc><a-d>" } # Replace tabs with spaces
  echo "%val{bufname} written"
}

define-command resource -params 1 %{
  eval %sh{
    file=$(mktemp)
    cat "$1" |
      sed 's/^def /def -override /'                        |
      sed 's/^define-command /def -override /'             |
      sed 's/^addhl /addhl -override /'                    |
      sed 's/^add-highlighter /addhl -override /'          |
      sed 's/^provide-module / provide-module -override /' |
      sed 's/^require-module /# require-module /'          |
      sed 's/^declare-user-mode /# declare-user-mode /'    |
      cat > "$file"
    printf %s "
      source $file
      nop %sh{
          rm $file
      }
    "
  }
  echo Reloaded %arg{1}
}

remove-hooks global reload-kak
hook -group reload-kak global BufWritePost (.*kakrc|.*\.kak) %{
   resource %val{hook_param}
}
map global normal <c-r> ':resource ~/.config/kak/kakrc<ret>'

hook global -group git-gutter-hooks BufCreate /.* %{
  try %{ git show-diff }
}
hook global -group git-gutter-hooks FocusIn /.* %{
  try %{ git-async update-diff }
}
hook global -group git-gutter-hooks BufReload /.* %{
  try %{ git-async update-diff }
}
hook global -group git-gutter-hooks BufWritePost /.* %{
  try %{ git-async update-diff }
}
hook global -group git-gutter-hooks NormalIdle /.* %{
  try %{ git-async update-diff }
}


#### Commands #####

# foo_bar → fooBar
# foo-bar → fooBar
# foo bar → fooBar
define-command camelcase %{
  exec '`s[-_<space>]<ret>d~<a-i>w'
}

# fooBar → foo_bar
# foo-bar → foo_bar
# foo bar → foo_bar
define-command snakecase %{
  exec '<a-:><a-;>s-|[a-z][A-Z]<ret>;a<space><esc>s[-\s]+<ret>c_<esc><a-i>w`'
}

# fooBar → foo-bar
# foo_bar → foo-bar
# foo bar → foo-bar
define-command kebabcase %{
  exec '<a-:><a-;>s_|[a-z][A-Z]<ret>;a<space><esc>s[_\s]+<ret>c-<esc><a-i>w`'
}

#### Highliters ####
add-highlighter global/git-diff flag-lines Default git_diff_flags
add-highlighter shared/non_ascii_characters regex '[^\x00-\x7f]+' '0:DiagnosticError'
add-highlighter global/ regex '[ \t]+$' '0:DiagnosticError'
add-highlighter global/ number-lines -relative -hlcursor
add-highlighter global/ wrap
add-highlighter global/ regex "%opt{comment_line}[ \t]*\b([A-Z][A-Z]+)\b" 1:default+br@comment
add-highlighter global/ show-matching
add-highlighter global/ show-whitespaces


#### Misc ####
colorscheme tokyonight
set global indentwidth 2
set global tabstop 2
set-option global ui_options "terminal_set_title=true"
set-option global ui_options "terminal_title=kak"
set-option global startup_info_version 40000000 # Disable startup changelog message

# Texture Plugin
set-option global texture_trunk_color "rgb:%opt{blue}"
set-option global texture_fork_color "rgb:%opt{blue}"
set-option global texture_limb_color "rgb:%opt{orange}"
set-option global texture_tile_color "rgb:%opt{bg_alt}"
set-option global texture_pane_color "rgb:%opt{comment}"
