#### Aliases ####
alias global bc delete-buffer
alias global bc! delete-buffer!

#### Keybindings ####
map global normal <a-1> ':buffer-previous<ret>'
map global normal <a-2> ':buffer-next<ret>'
map global normal <a-q> ':db<ret>'
map global normal <a-o> ':edit ~/.config/kak/kakrc<ret>'

map global normal <ret> <o>
map global normal <esc> ,hl  -docstring  'Clear Multi-cursor Selection'
map global normal <a-esc> <a-,>hl  -docstring  'Clear Multi-cursor Selection'

map global normal <c-a> ':inc-dec-modify-numbers + 1 <ret>'
map global normal <c-x> ':inc-dec-modify-numbers - 1 <ret>'
map global normal <c-n> ':edit -scratch<ret>'
map global normal <c-q> ':q<ret>'
map global normal <c-s> ':w<ret>'

map global normal <backspace> h<a-d>

map global normal F ':format<ret>'

define-command -hidden select-prev-word-part %{
  exec <a-/>[A-Z][a-z]+|[A-Z]+|[a-z]+<ret>
}
define-command -hidden select-next-word-part %{
  exec /[A-Z][a-z]+|[A-Z]+|[a-z]+<ret>
}
define-command -hidden extend-prev-word-part %{
  exec <a-?>[A-Z][a-z]+|[A-Z]+|[a-z]+<ret>
}
define-command -hidden extend-next-word-part %{
  exec ?[A-Z][a-z]+|[A-Z]+|[a-z]+<ret>
}
map global normal <a-w> :select-next-word-part<ret>
map global normal <a-W> :extend-next-word-part<ret>
map global normal <a-b> :select-prev-word-part<ret>
map global normal <a-B> :extend-prev-word-part<ret>

define-command _clipboard-paste -hidden -params 1 %{
  eval -save-regs c %sh{
    content=$(
      ~/.scripts/clip.sh out                   |
      sed 's/</#:____lt____:#/g'               |
      sed 's/>/#:____gt____:#/g'               |
      sed -E 's/#:____([a-z]{2})____:#/<\1>/g' |
      sed 's/;/<semicolon>/g'                  |
      sed 's/$/<ret>/g;'                       |
      sed 's/ /<space>/g'                      |
      sed 's/\t/<tab>/g'                       |
      sed ':a;N;$!ba;s/\n//g'                  |
      sed 's/<ret>$//'
    )
    echo "exec -draft o$content<esc>x_<dquote>cdx<a-d>"
    echo "exec <dquote>c$1"
  }
}
map global user p ':_clipboard-paste "p"<ret>' -docstring 'Paste clipboard to buffer after cursor'
map global user P ':_clipboard-paste "P"<ret>' -docstring 'Paste clipboard to buffer before cursor'
map global user R ':_clipboard-paste "R"<ret>' -docstring 'Replace buffer selection with clipboard'

define-command copy-and-comment %{
  evaluate-commands -save-regs ^ %{
    execute-keys -draft %{ZxyP: comment-line<ret>z}
  }
}
map global user d ':buffer *debug*<ret>' -docstring 'Enter debug buffer'
map global user <a-c> ':copy-and-comment<ret>' -docstring 'Copy line and place it as a comment above'
map global user c ':comment-line<ret>' -docstring 'Toggle line comment'
map global user C ':comment-block<ret>' -docstring 'Toggle block comment'
map global user y ':nop %sh{~/.scripts/clip.sh add "$kak_selection"}<ret>' -docstring 'Copy selection to clipboard'
map global user b ':_wez-fzf buffer<ret>' -docstring 'Open fuzzy buffer picker'
map global user f ':_wez-fzf pick<ret>' -docstring 'Open fuzzy file picker at git root'
map global user F ':_wez-fzf pick_cwd "%sh{pwd}" <ret>' -docstring 'Open fuzzy file picker at current working directory'
map global user o ':_wez-fzf pick_cbd "%val{buffile}"<ret>' -docstring "Open fuzzy file picker at current buffer's directory"
map global user / ':_wez-fzf global_search<ret>' -docstring "Open global text search picker at git root"

map global user r ":git apply --reverse<ret>" -docstring "Revert git changes on selections"

map global user <space> ': focus-toggle<ret>' -docstring "toggle selections focus"

map global goto w "<esc>:jumpJump<ret>" -docstring "Go to word"
map global goto W "<esc>:jumpJump -extend<ret>" -docstring "Go to word and extend selection"
map global goto <a-w> "<esc>:jumpJump -add<ret>" -docstring "Go to word and add to selection"

define-command _color-picker -hidden %{
  eval %sh{
    color="$(yad --color --picker --init-color="$kak_selection")"
    if [[ "$kak_selection" =~ \#[0-9a-fA-F]+ ]]; then
      echo "exec '<a-d>'<ret>"
    fi
    echo "exec 'i$color<esc>'<ret>"
  }
}

declare-user-mode run
map global normal <a-r> ':enter-user-mode run<ret>'
map global run  t ':_term down 30<ret>' -docstring 'Open Terminal Pane'
map global run  f ':_term left 20 lf "%val{buffile}"<ret>' -docstring 'Open File manager pane'
map global run  l ':_term down 40 lazygit<ret>' -docstring 'Open Lazygit pane'
map global run  r ':_run %val{buffile} false <ret>' -docstring 'Run current file interm'
map global run  c ':_run %val{buffile} false <ret>' -docstring 'Run current file and pipe output to fzf picker'
map global run  s '| sort<ret>' -docstring 'Sort selection'
map global run  p ':_color-picker<ret>' -docstring 'Color Picker'

declare-user-mode match
map global normal m ':enter-user-mode match<ret>'
map global match m m -docstring 'Match next matching pair'
map global match i ':match-inside<ret>' -docstring 'Match inside object'
map global match a ':match-around<ret>' -docstring 'Match around object'
map global match n ':match-next<ret>' -docstring 'Match next object'
map global match p ':match-prev<ret>' -docstring 'Match previous object'
map global match s ':match-surround-add<ret>' -docstring 'Surround selection with character'
map global match d ':match-surround-delete<ret>' -docstring 'Delete selection''s surrounding character'
map global match r ':match-surround-replace<ret>' -docstring 'Replace selection''s surrounding character'

#### hooks ####
hook global BufCreate .* %{
  expandtab
}

declare-option -docstring "Name of the git branch holding the current buffer" \
  str modeline_git_branch

declare-option -docstring "List of currently open buffers" \
  str modeline_buflist

declare-option -docstring "Curretly buffer filetype" \
    str modeline_filetype

hook global WinCreate .* %{
  hook window ModeChange pop:insert:normal %{
    eval %sh{
      [ "$kak_modified" = true ] && echo "write"
    }
  }
  hook window NormalIdle .* %{

    try %{
      eval %sh{
        [[ "$kak_buffile" =~ \*.+\* ]] && echo 'set window modeline_git_branch NONE' && exit
        branch=$(cd "$(dirname "${kak_buffile}")" && git rev-parse --abbrev-ref HEAD 2>/dev/null)
        [ -n "$branch" ] && printf 'set window modeline_git_branch " %%{%s}"' "$branch" && exit
        echo 'set window modeline_git_branch NONE'
      }
    }

    set-option global modeline_buflist ""
    evaluate-commands -no-hooks -buffer * %{
      set-option -add global modeline_buflist "%val{bufname} "
    }

    try %{
      eval %sh{
        filetype="$kak_opt_filetype"
        [ -n "$filetype" ] && echo "set window modeline_filetype $filetype" && exit
        [[ "$kak_bufname" =~ \*.+\* ]] && echo "set window modeline_filetype 'kak-star'" && exit
        echo "set window modeline_filetype 'txt'"
      }
    }
  }
}

declare-option -docstring "Current mode" \
  str modeline_mode 'NORMAL'

hook global ModeChange .* %{
  eval %sh{
    new_mode=$(echo $kak_hook_param | cut -d ':' -f 3 | sed 's/.*/\U&/' 2>/dev/null)
    printf 'set window modeline_mode "%%{%s}"' "${new_mode}"
  }
}

hook global InsertCompletionShow .* %{
  map window insert <tab>   '<c-n>'
  map window insert <s-tab> '<c-p>'
}
hook global InsertCompletionHide .* %{
  unmap window insert <tab>   '<c-n>'
  unmap window insert <s-tab> '<c-p>'
}

hook global -once KakBegin .* %{
  eval %sh{kak-lsp}
}

hook global WinCreate /.* %{
  lsp-enable-window

  set-option global modelinefmt '{cyan}%opt{modeline_git_branch}{default} | %val{bufname} | placeholder_buffer_count | %val{cursor_line}:%val{cursor_char_column} | %opt{modeline_mode} | %val{selection_count} | %opt{modeline_filetype} | '

  set-option global modelinefmt "%opt{lsp_modeline}| %opt{modelinefmt}"


  map global user l ':enter-user-mode lsp<ret>' -docstring 'LSP mode'

  map global goto d <esc>:lsp-definition<ret> -docstring 'LSP definition'
  map global goto r <esc>:lsp-references<ret> -docstring 'LSP references'
  map global goto y <esc>:lsp-type-definition<ret> -docstring 'LSP type definition'

  map global insert <tab> '<a-;>:try lsp-snippets-select-next-placeholders catch %{ execute-keys -with-hooks <lt>tab> }<ret>' -docstring 'Select next snippet placeholder'

  map global object a '<a-semicolon>lsp-object<ret>' -docstring 'LSP any symbol'
  map global object <a-a> '<a-semicolon>lsp-object<ret>' -docstring 'LSP any symbol'
  map global object f '<a-semicolon>lsp-object Function Method<ret>' -docstring 'LSP function or method'
  map global object t '<a-semicolon>lsp-object Class Interface Module Namespace Struct<ret>' -docstring 'LSP class or module'
  map global object d '<a-semicolon>lsp-diagnostic-object error warning<ret>' -docstring 'LSP errors and warnings'
  map global object D '<a-semicolon>lsp-diagnostic-object error<ret>' -docstring 'LSP errors'
}

hook global BufWritePre /.* %{
  try %{ exec -draft "%%s\h+$<ret>d" } # Trim trailing new lines
  try %{ exec -draft "%%s\t<ret>i<space><space><esc><a-d>" } # Replace tabs with spaces
  echo "%val{bufname} written"
}

define-command resource -params 1 %{
  eval %sh{
    file=$(mktemp)
    cat "$1" |
      sed 's/^def /def -override /'                        |
      sed 's/^define-command /def -override /'             |
      sed 's/^addhl /addhl -override /'                    |
      sed 's/^add-highlighter /addhl -override /'          |
      sed 's/^provide-module / provide-module -override /' |
      sed 's/^require-module /# require-module /'          |
      sed 's/^declare-user-mode /# declare-user-mode /'    |
      cat > "$file"
    printf %s "
      source $file
      nop %sh{
          rm $file
      }
    "
  }
  echo Reloaded %arg{1}
}

remove-hooks global reload-kak
hook -group reload-kak global BufWritePost (.*kakrc|.*\.kak) %{
   resource %val{hook_param}
}
map global normal <c-r> ':resource /home/kome/.config/kak/kakrc<ret>'

set-option global git_gutter_leave_space true
hook global -group git-gutter-setup BufCreate /.* %{
  add-highlighter buffer/git-diff flag-lines Default git_diff_flags
  try %{ git show-diff }

  hook buffer -group git-gutter-buffer FocusIn .* %{
    try %{ git-async update-diff }
  }
  hook buffer -group git-gutter-buffer BufReload .* %{
    try %{ git-async update-diff }
  }
  hook buffer -group git-gutter-buffer BufWritePost .* %{
    try %{ git-async update-diff }
  }
  hook buffer -group git-gutter-buffer NormalIdle .* %{
    try %{ git-async update-diff }
  }
}

#### Commands #####

  # foo_bar → fooBar
# foo-bar → fooBar
# foo bar → fooBar
define-command camelcase %{
  exec '`s[-_<space>]<ret>d~<a-i>w'
}

# fooBar → foo_bar
# foo-bar → foo_bar
# foo bar → foo_bar
define-command snakecase %{
  exec '<a-:><a-;>s-|[a-z][A-Z]<ret>;a<space><esc>s[-\s]+<ret>c_<esc><a-i>w`'
}

# fooBar → foo-bar
# foo_bar → foo-bar
# foo bar → foo-bar
define-command kebabcase %{
  exec '<a-:><a-;>s_|[a-z][A-Z]<ret>;a<space><esc>s[_\s]+<ret>c-<esc><a-i>w`'
}

#### Highliters ####
add-highlighter shared/non_ascii_characters regex '[^\x00-\x7f]+' '0:DiagnosticError'
add-highlighter global/ regex '[ \t]+$' '0:DiagnosticError'
add-highlighter global/ number-lines -relative -hlcursor
add-highlighter global/ wrap
add-highlighter global/ regex "%opt{comment_line}[ \t]*\b([A-Z][A-Z]+)\b" 1:default+br@comment
add-highlighter global/ show-matching
add-highlighter global/ show-whitespaces


#### Misc ####
colorscheme tokyonight
set global indentwidth 2
set global tabstop 2
set-option global ui_options "terminal_set_title=true"
set-option global ui_options "terminal_title=kak"
set-option global startup_info_version 40000000 # Disable startup changelog message

# Texture Plugin
set-option global texture_trunk_color "rgb:%opt{blue}"
set-option global texture_fork_color "rgb:%opt{blue}"
set-option global texture_limb_color "rgb:%opt{orange}"
set-option global texture_tile_color "rgb:%opt{bg_alt}"
set-option global texture_pane_color "rgb:%opt{comment}"
