#! /bin/sh

#Restart bspwm and sxhkd
super + shift + r
	bspc wm -r && notify-send BSPWN Restarted && \
	pkill -USR1 -x sxhkd && notify-send SXHd Restarted

#Quit bspwm
super + shift + Escape
	bspc quit

#Fullscreen Applicatioms
super + f
	 bspc node -t ~fullscreen

#Toggle tiling of a window
super + t
	 bspc node -t ~tiled

#Toggle floating of a window
super + d
	 bspc node -t ~floating

#Set layout to monocle
super + shift + f
	bspc desktop -l next

#Change to next or prev desktop
super + alt + {h,l}
	bspc desktop -f {prev,next}

#Move window to desktop
super + shift + {1,2,3,4,5,6,7,8,9}
	bspc node -f -d {1,2,3,4,5,6,7,8,9} --follow

#Change to specific Desktop
super + {1,2,3,4,5,6,7,8,9}
	bspc desktop -f {1,2,3,4,5,6,7,8,9}

#Close application
super + q
	bspc node -c

#Focus window
super + ctrl + {h,j,k,l}
	bspc node -f {west,south,north,east}.local.!hidden.window

#Move window around stack
super + ctrl + alt + {h,j,k,l}
	bspc node -f -s {west,south,north,east}.local.!hidden.window

#Resize tiled window out
super + shift + {h,j,k,l}
	bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}

#Resize tiled window in
super + shift + alt + {h,j,k,l}
	bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}

#Toggle compistor
super + c
	killall picom || picom

#Program launchers
super + a
	rofi -show drun

super + r
	rofi -show run

super + w
	source $HOME/.bash_profile && $BROWSER

super + e
	source $HOME/.bash_profile && $TERMINAL -e lf

super + Return
	source $HOME/.bash_profile && $TERMINAL

super + s
	com.spotify.Client

super + m
	reaper

super +  Tab
	rofi -show window

super + shift + e
	rofi -show emoji -emoji-mode copy

#Volume Keys
{super + shift + equal, XF86AudioRaiseVolume}
	pamixer -u && pamixer -i 5

{super + shift + minus, XF86AudioLowerVolume}
	pamixer -u && pamixer -d 5

{super + shift + m, XF86AudioMute}
	pamixer -t #mute

#Brightness Keys
{super + shift + bracketright, XF86MonBrightnessUp}
	light -A 5

{super + shift + bracketleft, XF86MonBrightnessDown}
	light -U 5

#Media Keys
{super + shift + period, XF86AudioNext}
	playerctl next

{super + shift + p, XF86AudioPlay}
	playerctl play-pause

{super + shift + comma, XF86AudioPrev}
	playerctl previous

#Bar
super + b
	killall polybar || polybar

#Screenshot
super + shift + Print
	/home/kome/.scripts/screenshot.sh

#Lock Screen
super + l
	eval $LOCK_SCRIPT

#Power
super + shift + {F4,F2}
	{poweroff,reboot}

super + shift + {c,v,s,d}
	$HOME/.scripts/clip.sh {copy,recopy,sel,del}

super + shift + b
	$HOME/.scripts/bm.sh
