#! /bin/sh

#Restart bspwm and sxhkd
super + shift + r
	bspc wm -r && notify-send BSPWN Restarted && \
	pkill -USR1 -x sxhkd && notify-send SXHd Restarted

#Quit bspwm
ctrl + alt + Escape
	bspc quit

#Fullscreen Applicatioms
super + f
	 bspc node -t ~fullscreen

#Toggle tiling of a window
super + t
	 bspc node -t ~tiled

#Toggle floating of a window
super + d
	 bspc node -t ~floating

#Set layout to monocle
super + shift + f
	bspc desktop -l next

#Change Desktop
ctrl + alt + {Left,Right}
	bspc desktop -f {prev,next}

#Move focused window to previous or next desktop
ctrl + shift + alt + {Left,Right}
	bspc node -f -d {prev,next} --follow

ctrl + shift + {1,2,3,4,5,6,7,8,9}
	bspc node -f -d {1,2,3,4,5,6,7,8,9} --follow

#Change to specific Desktop
ctrl + {1,2,3,4,5,6,7,8,9}
	bspc desktop -f {1,2,3,4,5,6,7,8,9}

#Close application
super + q
	bspc node -c

super + {Left,Down,Up,Right}
	bspc node -f {west,south,north,east}.local.!hidden.window

alt + shift + Tab
	bspc node -f prev.local.!hidden.window

#Resize tiled window out
super + shift + {Left,Down,Up,Right}
	bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}

#Resize tiled window in
super + shift + alt + {Left,Down,Up,Right}
	bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}

# #Move windows along the stack
# super + {Left,Down,Up,Right}
# 	bspc node -s {west,south,north,east} --follow

#Toggle compistor
super + c
	killall picom || picom

#Program launchers
super + a
	rofi -show drun

super + r
	rofi -show run

super + 1
	flatpak run app.zen_browser.zen

super + 2
	wezterm -e lf

{super + 3, ctrl + alt + t, super + Return}
	wezterm

super + 4
	flatpak run com.spotify.Client

super + 5
	reaper

super + Tab
	rofi -show window

super + e
	rofi -show emoji -emoji-mode copy

#Volume Keys
{super + shift + equal, XF86AudioRaiseVolume}
	pamixer -u && pamixer -i 5

{super + shift + minus, XF86AudioLowerVolume}
	pamixer -u && pamixer -d 5

{super + shift + m, XF86AudioMute}
	pamixer -t #mute

#Brightness Keys
{super + shift + bracketright, XF86MonBrightnessUp}
	light -A 5

{super + shift + bracketleft, XF86MonBrightnessDown}
	light -U 5

#Media Keys
{super + shift + period, XF86AudioNext}
	playerctl next

{super + shift + p, XF86AudioPlay}
	playerctl play-pause

{super + shift + comma, XF86AudioPrev}
	playerctl previous

#Bar
super + w
	killall polybar || polybar

#Screenshot
shift + Print
	/home/kome/.scripts/screenshot.sh

#Lock Screen
super + l
	magick /home/kome/.scripts/current_wallpaper.png -resize 1920x /home/kome/.scripts/current_wallpaper.png && \
	i3lock -i /home/kome/.scripts/current_wallpaper.png -ef

#Power
ctrl + shift + F4
	poweroff

ctrl + shift + F2
	reboot

super + shift + c
	$HOME/.scripts/clip.sh copy

super + shift + v
	$HOME/.scripts/clip.sh recopy

super + shift + s
	$HOME/.scripts/clip.sh sel
