#!/bin/sh

#Toggle Bar
super + b
	killall polybar || polybar

#Toggle compistor
super + c
	killall picom || picom

#Program launchers
super + w
	source ~/.bash_profile && $BROWSER

super + e
	source ~/.bash_profile && $TERMINAL -e lf

super + Return
	source ~/.bash_profile && $TERMINAL

super + s
	com.spotify.Client

super + m
	reaper

#Rofi
super + a
	rofi -show drun

super + r
	rofi -show run

super +  Tab
	rofi -show window

super + shift + e
	rofi -show emoji -emoji-mode copy

#Screenshot
super + shift + Print
	/home/kome/.scripts/screenshot.sh

#Lock Screen
super + l
	eval $LOCK_SCRIPT

#Volume Keys
{super + shift + equal, XF86AudioRaiseVolume}
	pamixer -u && pamixer -i 5

{super + shift + minus, XF86AudioLowerVolume}
	pamixer -u && pamixer -d 5

{super + shift + m, XF86AudioMute}
	pamixer -t #mute

#Brightness Keys
{super + shift + bracketright, XF86MonBrightnessUp}
	light -A 5

{super + shift + bracketleft, XF86MonBrightnessDown}
	light -U 5

#Media Keys
{super + shift + period, XF86AudioNext}
	playerctl next

{super + shift + p, XF86AudioPlay}
	playerctl play-pause

{super + shift + comma, XF86AudioPrev}
	playerctl previous

super + shift + r
	dkcmd restart && notify-send DK Restarted && \
	pkill -USR1 -x sxhkd && notify-send SXHd Restarted

# quit dk
super + shift + Escape
	dkcmd exit

# focus window
super + ctrl + {h,j,k,l}
	dkcmd win focus {left,down,up,right}

# close window, swap tiled window in/out of master
super + {q,space}
	dkcmd win {kill,swap}

# close window, swap tiled window in/out of master, cycle tiled windows in place
# super + {q,space,Tab}
# 	dkcmd win {kill,swap,cycle}

# toggle fullscreen and fake fullscreen (enable manipulating fullscreen window)
super + f
	dkcmd win full

# toggle floating, sticky, or scratchpad
super + {d,s,u}
	dkcmd win {float,stick,scratch}
	# alternatively to scratch a window by class "scratchpad"
	#dkcmd win {float,stick,scratchpad scratch}

# # move window, signed (+/-) for relative changes, for tiled windows
# # y coord changes will move the window up/down the stack
# alt + shift + {h,j,k,l}
# 	dkcmd win resize {x=-20,y=+20,y=-20,x=+20}

# resize window, signed (+/-) for relative changes
super + shift + {h,j,k,l}
	dkcmd win resize {w=-20,h=-20,h=+20,w=+20}

#Change to next or prev desktop
super + alt + {h,l}
	dkcmd ws view {prev,next}

super + shift + {1-9}
	dkcmd ws follow {1-9}

#Change to specific Desktop
super + {1-9}
	dkcmd ws view {1-9}

# change active workspace layout to tiled
super + t
	dkcmd set layout tile

#Power
super + shift + {F4,F2}
	{poweroff,reboot}

# clip.sh
super + shift + {c,v,s,d}
	$HOME/.scripts/clip.sh {copy,recopy,sel,del}

super + shift + b
	$HOME/.scripts/bm.sh
