[manager]

sort_by = "natural"
show_hidden = true

[opener]

text = [
  {run = 'helix "$@"', block = true}
]

[open]
rules = [
	{ mime = "text/*", use = "text" },
	{ mime = "image/*", use = "image" },

	# { mime = "application/json", use = "text" },
	{ name = "*.json", use = "text" },

	# Multiple openers for a single rule
	{ name = "*.html", use = [ "browser", "text" ] },
]
