[mgr]

sort_by = "natural"
show_hidden = true
ratio = [1, 2, 2]

[opener]

text = [
  { run = '/home/kome/.dotfiles/.scripts/yazi-helix.sh "$@"', block = true }
]
image = [
  { run = 'xdg-open "$@"', block = false}
]

[open]
rules = [
	{ mime = "text/*", use = "text" },
	{ mime = "image/*", use = "image" },

	{ mime = "application/json", use = "text" },
	{ mime = "application/javascript", use = "text" },
	{ name = "*.nelua", use = "text" },
	{ name = "*.env", use = "text" },
	{ name = "*.tsx", use = "text" },
	{ name = "*.ts", use = "text" },
	# { name = "*.json", use = "text" },

	# Multiple openers for a single rule
	{ name = "*.html", use = [ "browser", "text" ] },
]
