[mgr]

sort_by = "natural"
show_hidden = true
ratio = [1, 2, 2]

# [manager]

[opener]

text = [
  { run = '/home/kome/.dotfiles/.scripts/yazi-helix.sh "$@"', block = true }
]

[open]
rules = [
	{ mime = "text/*", use = "text" },
	{ mime = "image/*", use = "image" },

	{ mime = "application/json", use = "text" },
	{ mime = "application/javascript", use = "text" },
	# { name = "*.json", use = "text" },

	# Multiple openers for a single rule
	{ name = "*.html", use = [ "browser", "text" ] },
]
