#! /bin/sh

export LOGOUT_SCRIPT="bspc quit"
export LOCK_SCRIPT="magick /tmp/current_wallpaper.png -resize 1920x /tmp/current_wallpaper.png && i3lock -i /tmp/current_wallpaper.png -ef"

run() {
  if [ -z $(pgrep -f "$1") ]; then
    "$@" &
  fi
}

#autostart
run source $HOME/.bash_profile
run xrdb $XRESOURCES
run eww open bar
run sxhkd
run xsetroot -cursor_name left_ptr
run xset led 3 # For generic led keyboards
run picom
run caffeine start
run dunst
run redshift
run xfce4-power-manager
run $HOME/.scripts/bg.sh
run $HOME/.scripts/low_battery.lua
run $HOME/.scripts/bspwm-eww_bar.sh
run $HOME/.scripts/bspwm-master-stack.sh
run /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
run dbus-update-activation-environment --systemd --all

touchegg_count=$(pgrep -xc touchegg)
[ "$touchegg_count" -le 1 ] && touchegg & # systemctl start touchegg counts as 1

#bspwm
if [ -n "$(xrandr | grep "HDMI-1 connected")" ]; then
  bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8
  bspc monitor HDMI-1 -d 9
else
  bspc monitor HDMI-1 -r
  bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9
fi

bspc config border_width 1
bspc config window_gap 10

# bspc config split_ratio          0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true
# bspc config pointer_follows_focus true
# bspc config pointer_follows_monitor true

bspc config focused_border_color \#9ABDF5
bspc config normal_border_color \#404E65FF

bspc rule -a yad state=floating center=true
bspc rule -a xdman-Main state=floating center=true
bspc rule -a Localsend state=tiled
bspc config external_rules_command "$HOME/.config/bspwm/external_rules"
