#! /bin/sh

#autostart
pgrep -x sxhkd > /dev/null || sxhkd &

#bspwm
bspc monitor -d 1 2 3 4 5 6 7 8 9
 
bspc config border_width         2
bspc config window_gap           0

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc config focused_border_color \#0B0BB4
bspc config normal_border_color \#03032F

bspc rule -a zenity state=floating center=true
bspc rule -a smile state=floating  center=true
bspc rule -a pavucontrol state=floating center=true
bspc rule -a Blueman-manager state=floating center=true
bspc rule -a gnome-calculator state=floating center=true
bspc rule -a xdman-Main state=floating center=true
bspc rule -a Localsend state=tiled
bspc rule -a i3lock state=fullscreen

bsp-layout set tall 1 --master-size 0.5
bsp-layout set tall 2 --master-size 0.5
bsp-layout set tall 3 --master-size 0.5
bsp-layout set tall 4 --master-size 0.5
bsp-layout set tall 5 --master-size 0.5
bsp-layout set tall 6 --master-size 0.5
bsp-layout set tall 7 --master-size 0.5
bsp-layout set tall 8 --master-size 0.5
bsp-layout set tall 9 --master-size 0.5

#autostart
xsetroot -cursor_name left_ptr &
xset led 3 &
pgrep -x picom > /dev/null || picom &
pgrep -x Nitrogen.sh > /dev/null  || /home/kome/.scripts/Nitrogen.sh &
pgrep -x polybar > /dev/null || polybar &
pgrep -x nm-applet > /dev/null || nm-applet &
pgrep -x blueman-applet > /dev/null || blueman-applet &
pgrep -x caffeine > /dev/null ||caffeine start &
pgrep -x dunst > /dev/null || dunst &
pgrep -x redshift > /dev/null || redshift &
pgrep -x gpaste-daemon > /dev/null || gpaste-client start &
pgrep -x mpris-proxy > /dev/null || mpris-proxy &
touchegg & # systemctl enable touchegg
pgrep -f "low_battery.lua" > /dev/null || lua /home/kome/.scripts/low_battery.lua &
playerctl status --format '{{ playerName }}' --follow > /tmp/player-last &

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
/lib/xdg-desktop-portal-gnome &
dbus-update-activation-environment --systemd --all &
"/opt/xdman/jre/bin/java" -Xmx1024m -jar "/opt/xdman/xdman.jar" -m &

xinput set-prop "VEN_27C6:00 27C6:0D43 Touchpad" "libinput Natural Scrolling Enabled" 1 &
xinput set-prop "VEN_27C6:00 27C6:0D43 Touchpad" "libinput Middle Emulation Enabled" 1 &
xinput set-prop "VEN_27C6:00 27C6:0D43 Touchpad" "libinput Tapping Enabled" 1 &

