# Flatpak

add = "flatpak install #:? -y"
remove = "flatpak uninstall #:? -y --delete-data"
upgrade = "flatpak upgrade -y"

plural_name = "flatpaks"

hook_name = "flatpaks"

[config]
many_args = true
