#!/usr/bin/env bash

system_files_path="$HOME/.config/rebos/system_files"
greetd_path="$system_files_path/greetd"
regreet_path="$system_files_path/regreet.toml"
limits_path="$system_files_path/limits.conf"
touchpad_30_path="$system_files_path/30-touchpad.conf"

# Taken from OgloTheNerd
overwrite_file () {
  use_sudo=0

  src="$1"
  dest="$2"

  [[ "$OFSUDO" == 1 ]] && use_sudo=1

  cmd_to_exec="cp"

  [[ "$use_sudo" == 1 ]] && cmd_to_exec="sudo ${cmd_to_exec}"

  exit_status=0

  $cmd_to_exec "$src" "$dest" > /dev/null 2>&1 || exit_status=1

  echo -en "\033[1;93mOVERWRITE\033[0m \033[0;96m${src}\033[0m -> \033[0;95m${dest}\033[0m "

  if [[ "$exit_status" == 0 ]]; then
    echo -e "\033[1;92m(^-^)\033[0m"
  else
    echo -e "\033[1;91m(T~T)\033[0m"
  fi

  return $exit_status
}

if ! cmp -s "$greetd_path" /etc/pam.d/greetd; then
  OFSUDO=1 overwrite_file "$greetd_path" /etc/pam.d/greetd || exit 1
fi

if ! cmp -s "$regreet_path" /etc/greetd/regreet.toml; then
  OFSUDO=1 overwrite_file "$regreet_path" /etc/greetd/regreet.toml || exit 1
fi

if ! cmp -s "$limits_path" /etc/security/limits.conf; then
  OFSUDO=1 overwrite_file "$limits_path" /etc/security/limits.conf || exit 1
fi

if ! cmp -s "$touchpad_30_path" /etc/X11/xorg.conf.d/30-touchpad.conf; then
  OFSUDO=1 overwrite_file "$touchpad_30_path" /etc/X11/xorg.conf.d/30-touchpad.conf || exit 1
fi

# Proper nemo open in terminal
gsettings set org.cinnamon.desktop.default-applications.terminal exec /home/kome/.scripts/wezterm_nemo.sh

# Sober overrides
flatpak override --user --filesystem=xdg-run/app/com.discordapp.Discord:create --filesystem=xdg-run/discord-ipc-0 --device=input org.vinegarhq.Sober
